### PR TITLE
Fix copy to clipboard not working in firefox

### PR DESCRIPTION
**Pull request by fawazahmed0**
Fix https://github.com/sunnah-com/website/issues/98
I have tested the fix locally

### CODE REVIEW

**Comment by musa11971** [comment]
@ahadith @hasankhan could this fix please be merged? This bug is quite a nuisance when using the website in Firefox. JazaakAllahu khayr

**Review by hasankhan — APPROVED** [review]

**Comment by hasankhan** [comment]
jazakAllah khair

**Comment by fawazahmed0** [comment]
Thank you for the website, it's very useful for everyone.

**Comment by ahadith** [comment]
Jazakumullahu khair - I've deployed this to the server.

**Comment by fawazahmed0** [comment]
Salam alaykum, I made an hadith api. you can take the data from my api, so that it benefits everyone.
Here is the link: https://github.com/fawazahmed0/hadith-api#readme

**Pull request merged**
