### PR TITLE
Decoupled styles from HTML and added webfonts

### PR DESCRIPTION
**Pull request by fsid**
- Simplified HTML by removing elements that could be replaced simply by adjusting the margin around other items, like hline and empty divs with only heights defined.

- Moved search icon and hadith icon styling to CSS

- Use CSS logic for Hadith icons, removed template logic

- Where possible, replaced logical implementation of styles with classes

- Responsive:

  - Improved home page styling

  - Changed hadith icon placement from top to half-cut left/right of the text (half off screen)

- Added webfonts:

  - _Noto Nastaliq Urdu_ for Urdu text

  - _KFGQPC Uthman Taha Naskh_  (+bold) for Arabic text

### CODE REVIEW

**Comment by hasankhan** [comment]
Can you please post screenshot of changes before and after?

**Comment by ahadith** [comment]
> Can you please post screenshot of changes before and after?

Except for the font changes, there should be no changes in the display whatsoever. The point of the commit is to remove any styling from the actual HTML and push it into the CSS file.

**Comment by hasankhan** [comment]
Alright, taking a look.

**Comment by hasankhan** [comment]
collection
a

home


hadith english

**Comment by ahadith** [comment]
The first image is a good find @hasankhan. @fsid if you want to see it, go to the Bulugh al-Maram collection.

I don't see anything off in the second and third images - am I missing something?

**Comment by hasankhan** [comment]
Looks good to me.

**Comment by fsid** [comment]
Thanks for the find Hasan. Didn't realize we were using the bars on the prod site, I had not tested that. The fix has been added.

**Comment by hasankhan** [comment]
Can you please post an updated screenshot?

**Comment by ahadith** [comment]
> Can you please post an updated screenshot?

Screenshot from 2020-06-02 21-36-00

It works alhamdulillah.

**Comment by fsid** [comment]
Thanks for the merge @ahadith 
I have a couple of more improvements. But they can be merged later. JazakAllah

**Pull request merged**
