### PR TITLE
Bugfix: Copybutton on phone /search does copy now the link also, in shaa Allah.

### PR DESCRIPTION
**Pull request by TarikHaci**
Bismillahrahmanirahim
I couldn't open Docker due to 
Invalid Configuration – yii\base\InvalidConfigException
yii\web\Request::cookieValidationKey must be configured with a secret key.
Error. So I iam asking pull without testing.

### CODE REVIEW

**Comment by ahadith** [comment]
Assalamu `alaykum Br Tarik

Welcome! I just pushed a change to the sample `.env.local` file that adds the right parameter. Please update your repo and run docker build again.

I look at your change and I don't think it does what the title suggests? The current commit simply prints the link on the search results page. It looks like this:

Screenshot from 2021-03-28 18-52-49

Also tagging @naushervan to follow this PR.

**Comment by naushervan** [comment]
@TarikHaci If I understand the problem you seem to be facing, there is a drop-down menu button at the right side of the Copy button in the form of a small triangle icon pointing downwards. When you press it and open the drop-down menu, you can select which Ḥadīth fields to copy to the clipboard. Kindly try that out and tell me if that solves the issue you were facing. JazākAllāhu khayrā.

**Comment by TarikHaci** [comment]
We aleykum esselam we rhametullahi we berekatuh.

Forgive me brothers as stated I didn't had working debug environment to test if it was working or not.
Now finally the website runs, but the search doesn't work. I have made a video to explain the bug of the site + problem of running it locally, in shaa Allah.

[https://youtu.be/2zxHFuYcBO8](https://youtu.be/2zxHFuYcBO8)
Sorry for your time.

**Comment by ahadith** [comment]
Jazakallahu khair brother @TarikHaci for the video explaining the problems. I've made two issues and linked them to this pull request. @naushervan can you please take a look? @fsid can you look at how to not link the area around the copy link? (i.e. issue https://github.com/sunnah-com/website/issues/87). 

Secondly, as for the Solr - we haven't containerized Solr yet unfortunately. I've been meaning to do that but have not completed it. Apologies for wasting your time. @TarikHaci I will send you the Solr index and instructions on how to get the Solr server running on your system.

**Review by TarikHaci — COMMENTED** [review]
@ahadith Could you test this one also out for the mobile?
It only should fix that for the mobile it copies also the link.
Thanks for your time, In shaa Allah it works!

**Comment by ahadith** [comment]
Salam Br Tarik

We fixed the issue by removing the copy button from mobile search results. This is because it leads to added complexity (we would need to fetch the full hadith rather than just the portion with the search text and store it separately). Thank you for your attention to the matter and we hope to see more contributions from you in sha Allah! Please let me know how I can help.

**Pull request closed without merging**
